Klassen
Doma1612/video-portal-backend pull request #4
Opened 2023-11-03 10:22 UTC by LukasMeyerZuB

Klassen Implementierung

2023-11-03 12:41 UTC, Doma1612 requested changes

2023-11-03 12:41 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/VideoTO.java
> +            List<Video> videos) {
Liste weg. Auf keinen Fall Video Objekt in TO Objekt rein, das bricht die Kapselung.

2023-11-03 13:48 UTC, LukasMeyerZuB commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/VideoTO.java
> +            List<Video> videos) {
Ok ja das macht Sinn.

2023-11-03 13:54 UTC, LukasMeyerZuB commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/impl/Thema.java
> +    private List<Kategorie> kategorien;
Ich hätte gesagt das zu einem bestimmten Thema verschiedene Kategorien gehören. Deshalb die OneToMany Beziehung. Und diesen Kategorien werden dann die Videos zugeordnet. Um das abzubilden speichern wir dann einfach die Ids der Kategorien bei den Videos. Dann fällt auch die Videoliste bei den Kategorien weg.

2023-11-03 13:54 UTC, LukasMeyerZuB commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/impl/Thema.java
> +    @OneToMany(mappedBy = "thema")
Meinst du das Attribut ?

2023-11-03 14:00 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/impl/Thema.java
> +    private List<Kategorie> kategorien;
Ist die Kategorie nicht über dem Thema? Also jedes Thema ist eine (Unter)Kategorie aber nicht jede Kategorie ist ein Thema?

2023-11-03 14:00 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/impl/Thema.java
> +    @OneToMany(mappedBy = "thema")
Ich meine dass Groß und Kleinschreibung bei JPA wichtig ist

2023-11-03 14:04 UTC, philippkuehling commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/impl/Video.java
> +            Kategorie kategorie) {
Wir haben mehrere Videos, die einer Kategorie angehören (ManyToOne passt)
Wir haben eine Kategorie, die mehrere Unterkategorien haben. Dann müssten wir doch in der Entity Kategorie  @OneToMany(mappedBy = "kategorie") machen, oder?

2023-11-03 14:12 UTC, LukasMeyerZuB commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/impl/Thema.java
> +    @OneToMany(mappedBy = "thema")
Ah ja klar

2023-11-03 14:12 UTC, LukasMeyerZuB commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/impl/Thema.java
> +    private List<Kategorie> kategorien;
Es wird zwischen 2 Rollen unterschieden. Der Administrator kann Themenbereiche anlegen, ändern und löschen. Zu einem Themenbereiche können beliebige Unterkategorien festgelegt werden. In jedem Thema bzw. jeder Kategorie können beliebig viele Videos bereitgestellt werden. - > Für mich steht darin, dass Themen übergeordnet sind. Zu einem Thema gehören mehrere Kategorien. Und die KategorieIds speichern wir beim Video. In Bezug auf die Datenstruktur wäre also alles ersichtlich. Denn bei der Kategorie ist die Id eines Themas gespeichert, wodurch man immer alle nötigen Informationen zurückverfolgen kann.

2023-11-06 15:53 UTC, Doma1612 requested changes

2023-11-06 15:53 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/ThemaTO.java
> +	List<Unterkategorie> unterkategorien;
Hier darf kein normales Objekt rein, sondern da muss UnterkategorieTO rein

2023-11-06 15:53 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/ThemaTO.java
> +	public void setUnterkategorien(List<Unterkategorie> unterkategorien) {
Hier auch

2023-11-06 15:53 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/VideoTO.java
>      Thema thema;
Bitte ThemaTO statt Themaobjekt.

2023-11-06 15:56 UTC, Doma1612 commented
@LukasMeyerZuB Bitte `mvn spotless:check` und `mvn spotless:apply` lokal bei dir auf der dev branch ausführen und dann nochmal den formatierten Code nachdem du alle Änderungen drin hast pushen.

2023-11-07 10:24 UTC, LukasMeyerZuB commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/ThemaTO.java
> +	List<Unterkategorie> unterkategorien;
Ok verstehe ich. Aber ich weiß nicht wie das umgesetzt werden soll, da dadurch auch alle anderen Klassen betroffen sind. Vielleicht passt du es einmal selbst bei Gelegenheit an. Habe es in Vergangenheit dann wohl leider falsch gemacht :) .

2023-11-07 10:26 UTC, LukasMeyerZuB commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/ThemaTO.java
> +	List<Unterkategorie> unterkategorien;
Kannst du so schon auf den Code zugreifen ?

2023-11-10 12:22 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/VideoTO.java
> +            List<Video> videos) {
Also nochmal: Hier muss ein VideoTO Objekt rein.

2023-11-10 12:22 UTC, Doma1612 commented on video-portal-backend/SP_Video_Portal_Video_EJB/src/main/java/de/videoportal/video/entity/ThemaTO.java
> +	List<Unterkategorie> unterkategorien;
Ich kann leider nicht auf den Fork zugreifen. Das muss aber einfach eine UnterkategorieTO sein.

2023-11-15 07:37 UTC, Doma1612 commented
Klassenanpassung in anderer Branch vorgenommen

2023-11-15 07:37 UTC, closed without merging